
title: Maddy Tipping
email: contact@gabelynch.com
author: Gabe Lynch
url: https://gabe3l.github.io/maddytipping

lang: en
theme: wind-theme

collections:
  pages:
    output: true
    permalink: /:path/