
title: Maddy Tipping
email: contact@gabelynch.com
author: Gabe Lynch
url: https://gabe3l.github.io/maddytipping

lang: en

plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/